- Infrastructure:
    - RPi:
        icon: raspberry-pi.png
        description: raspJERRYpi
        siteMonitor: "http://192.168.0.2"

    - Caddy:
        icon: caddy.png
        description: Reverse proxy
        href: "http://192.168.0.2"
        siteMonitor: "http://192.168.0.2"

    - WireGuard:
        icon: wireguard.png
        description: VPN server
        href: "https://vpn.razzula.uk"
        siteMonitor: "https://vpn.razzula.uk"

- Services:
    - Vaultwarden:
        icon: vaultwarden.png
        description: Password manager
        href: "https://vault.razzula.uk"
        siteMonitor: "https://vault.razzula.uk/alive"

    - Homepage:
        icon: homepage.png
        description: This dashboard
        siteMonitor: "http://192.168.0.2:3000"
