- Infrastructure:
    - RPi:
        icon: raspberry-pi.png
        description: raspJERRYpi
        siteMonitor: "https://vault.razzula.uk:983"

    - Caddy:
        icon: caddy.png
        description: Reverse proxy
        href: "https://vault.razzula.uk:984/config/"
        siteMonitor: "https://vault.razzula.uk:984/config/"
        # widget:
        #     type: caddy
        #     url: "https://vault.razzula.uk:984" # /reverse_proxy/upstreams

    - Pi-Hole:
        icon: pi-hole.png
        description: DNS server
        href: "https://vault.razzula.uk:982/admin"
        siteMonitor: "https://vault.razzula.uk:982"
        # widget:
        #     type: pihole
        #     url: "https://vault.razzula.uk:982" # ???
        #     version: 6
        #     key: "${PIHOLE_PASSWORD}"


    - WireGuard:
        icon: wireguard.png
        description: VPN server
        href: "https://vault.razzula.uk:981"
        siteMonitor: "http://host.containers.internal:781"
        # widget:
        #     type: wgeasy
        #     url: "https://vault.razzula.uk:981" # /api/client
        #     version: 2
        #     username: "${WIREGUARD_USERNAME}"
        #     password: "${WIREGUARD_PASSWORD}"

    - Cloudflare DDNS:
        icon: cloudflare.png
        description: Dynamic DNS updater

- Services:
    - Vaultwarden:
        icon: vaultwarden.png
        description: Password manager
        href: "https://vault.razzula.uk:983"
        siteMonitor: "http://host.containers.internal:783/alive"

    - Homepage:
        icon: homepage.png
        description: This dashboard
        siteMonitor: "https://vault.razzula.uk:983"
